name: quantecon
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11
  - anaconda=2024.06
  - pip
  - pip:
    - jupyter-book
    - docutils
    - quantecon-book-theme==0.7.2
    - sphinx-tojupyter
    - sphinxext-rediraffe
    - sphinx-exercise
    - sphinx-proof
    - ghp-import
    - sphinxcontrib-youtube
    - sphinx-togglebutton
    - sphinx_reredirects
    # Sandpit Requirements
    # - PuLP
    # - cvxpy
    # - cvxopt
    # - cylp
    # - array-to-latex
    # - prettytable
